### PR TITLE
check the field within the data, not just the existence of data

### PR DESCRIPTION
**Pull request by goggledefogger**
Tried using 1.0.6 for the first time, noticed this bug, seem like the right fix?

### CODE REVIEW

**Comment by jessetane** [comment]
Hm, what is the actual bug? This code could throw if data === null, which could sometimes be the case, no?

**Comment by jessetane** [comment]
I know, really hard to debug this without any tests 😬

**Comment by goggledefogger** [comment]
Without the fix, the fields that are deleted in memory get set to "undefined" when submitted to Firebase, and Firebase chokes on undefined values. With the fix, those undefined values get actually deleted, which allows the Firebase write to succeed

**Comment by jessetane** [comment]
Hm, but your patch is in the bit where memory is updated when coming back FROM firebase, not to it.

**Comment by jessetane** [comment]
You're right that firebase will choke if you try to send it undefined - to delete fields, you need to set them to null.

**Comment by goggledefogger** [comment]
I think what happens is that you're right, this is where things get set to undefined, and then when i call update next, it sends those undefined values to Firebase and chokes

**Comment by jessetane** [comment]
I don't think firebase will send you undefined, is it possible that somehow code outside is setting props to undefined accidentally instead of doing `delete model.data[field]` or `model.data[field] = null`?

**Comment by jessetane** [comment]
Just looked at this again, and I think maybe the problem is that if the field is deleted at firebase, but NOT from memory, it will end up as undefined here when the update comes through, which would then cause subsequent updates to fail. So this patch is almost correct, you just need to defend against the case where data might be null or undefined - you should be able to just do `data && data[field]`.

**Comment by goggledefogger** [comment]
Ah good catch, patch updated, look good?

**Comment by jessetane** [comment]
word, feel free to release

**Comment by goggledefogger** [comment]
1.0.7 released

**Comment by goggledefogger** [comment]
ah crap, forgot to update the version in package.json

**Comment by jessetane** [comment]
you should be able to force push a new tag

**Pull request merged**
